Creazione form registrazione
Federico-Cereda/ASPNetCoreReactProducts pull request #47
Opened 2023-12-15 17:49 UTC by Federico-Cereda

2023-12-15 17:50 UTC, Federico-Cereda commented
![](https://github.trello.services/images/mini-trello-icon.png) [[CarrelloSpesa] Ceazione form registrazione](https://trello.com/c/ZlEqoPVt/157-carrellospesa-ceazione-form-registrazione)

2023-12-15 23:43 UTC, claudiosantaniello requested changes

2023-12-15 23:43 UTC, claudiosantaniello commented on react-shop/src/model/utente.ts
> +    idRuolo: number;
sarebbe il caso di avere anche il campo nomeRuolo: string

2023-12-18 15:31 UTC, claudiosantaniello commented on react-shop/src/model/utente.ts
> +    idRuolo: number;
dopo una verifica da parte di @Federico-Cereda  posso confermare che sarà un punto relativo alla gestione dell'accesso alle pagine

2023-12-18 15:33 UTC, claudiosantaniello approved these changes
after internal catch-up. The PR looks good. It's approved

2023-12-18 15:35 UTC, merged